name: Build and publish

on:
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cached build
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: harrisonai/terraform:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Show image history
        run: docker image history harrisonai/terraform

      - name: Build the image
        run: make build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        if: github.event_name == 'release'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish the image
        if: github.event_name == 'release'
        run: make publish
        env:
          TAG: ${{ github.ref_name }}
